services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://127.0.0.1:3000/health >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 2s
